Only Generate an ideal dockerfile for %s with best prectices. Do not provide any description
include:
- base image
- installing dependencies
- setting working directory
- adding source code
- running the application